#! /bin/bash
set -e

PIDFILE=$HOME/scalex.pid

if [ -e $PIDFILE ]; then
    kill $(cat $PIDFILE) || echo "Failed to kill"
fi

nohup java -Dscala.usejavacp=true -jar scalex-assembly-3.0-SNAPSHOT.jar http --port 8000 > stdout.log 2> stderr.log &
echo $! > $PIDFILE
