#! /bin/bash
set -e

PIDFILE=$HOME/scalex.pid

if [ -e $PIDFILE ]; then
    kill $(cat $PIDFILE) || echo "Failed to kill"
fi

nohup java -Dscala.usejavacp=true -jar scalex-assembly-3.0-SNAPSHOT.jar --listen 8000 &
echo $! > $PIDFILE
