- hosts: scalex-servers
  remote_user: ec2-user
  tasks:

  - name: Use Elasticsearch's repos
    sudo: yes
    copy: src=elasticsearch.repo dest=/etc/yum.repos.d/

  - name: Install Elasticsearch
    sudo: yes
    yum: name=elasticsearch state=present

  - name: Start Elasticsearch
    service: name=elasticsearch state=started
    sudo: yes

  - name: Install Nginx
    sudo: yes
    yum: name=nginx state=present
  - name: Rewrite nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    sudo: yes
  - service: name=nginx state=reloaded
    sudo: yes
  - name: Use Bintray's RPM repository
    sudo: yes
    copy: src=bintray-sbt-rpm.repo dest=/etc/yum.repos.d/
  - name: Install sbt to use Scala
    sudo: yes
    yum: name=sbt state=present
  - name: Install Java 8
    sudo: yes
    yum: name=java-1.8.0-openjdk state=present
  - name: Use Java 8 as default
    sudo: yes
    command: update-alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
  - name: Clone scalex-web
    git: repo=https://github.com/kzys/scalex-web.git dest=~ec2-user/scalex-web

  - synchronize: src=../target/scala-2.11/scalex-assembly-3.0-SNAPSHOT.jar dest=~ec2-user/scalex-assembly-3.0-SNAPSHOT.jar

  - name: Copy scalex_3.0.0
    copy: src=../scalex_3.0.0.scalex dest=~ec2-user

  - name: Make ec2-user's directory executable
    file: path=~ec2-user state=directory mode=o+rx

  - name: Make scalex-web's directory executable
    file: path=~ec2-user/scalex-web state=directory mode=o+rx

  - name: Make scalex-web's files readable
    file: path=~ec2-user/scalex-web state=directory mode=o+r recurse=yes

  - copy: src=run-scalex dest=~ec2-user mode=u+x
  - command: ~ec2-user/run-scalex
